src/pages/verify/e-ids/danish-mitid.mdx, src/pages/verify/getting-started/oidc-intro.mdx
@mickhansen Based off https://github.com/criipto/document-signatures-docs/pull/3
=> Scope value anatomy

src/components/GraphQLExplorer.tsx
https://trello.com/c/bGRgT3rr/300-when-asking-for-crendentials-at-the-interactive-demo-they-should-be-validated-you-can-enter-wrong-credentials-and-be-shown-to-in
=> validate credentials for the graphql explorer/examples

src/pages/verify/guides/appswitch.mdx
scenarios, instead of the current 302 Redirect with Location header response.
Related to https://github.com/GreanTech/identityprovider/pull/459
=> Added description of how to get a 200 OK JSON response in appswitch

src/pages/verify/guides/appswitch.mdx
of the MitID test app versions.
=> Added description about some of the slightly surprising features

src/components/MdxProvider.tsx, src/layouts/mdx.tsx, src/pages/verify/guides/appswitch.mdx
Not the prettiest solution, but it works :)
=> add a workaround for duplicate headers

src/pages/verify/guides/faq.mdx
Mostly to allow developers to search for `Unknown Access Code`
=> add FAQ page with unknown access code information

src/pages/verify/e-ids/norwegian-bankid.mdx
install the test app in the first place, I have asked Bidbax for the
current procedure.
When testing this guide, please try to install and activate the test-version of the app on a phone that does not already have it installed.
=> First draft at activation guide. It is not clear yet how to get to

src/pages/verify/e-ids/norwegian-bankid.mdx
Added info about MVA obligation or not for customers.
=> Update to No bankID - Biometrics demands

src/pages/verify/e-ids/norwegian-bankid.mdx
Also changed "Existing customer" line, by removing text.
=> Added question to NO BankID application questions

src/components/ConsentRevocation.tsx, src/pages/verify/e-ids/danish-mitid.mdx, src/pages/verify/e-ids/danish-nemid.mdx, src/pages/verify/e-ids/norwegian-bankid.mdx
[Pending QA of the runtime and management API changes]
=> Added description of how the consent features work for NO and DK.

src/components/MdxProvider.tsx, src/layouts/mdx.tsx, src/pages/verify/integrations/aspnet-core-v6.mdx, src/pages/verify/integrations/aws-cognito.mdx, src/pages/verify/integrations/nodejs-express.mdx
Compare https://deploy-preview-33--criipto-docs.netlify.app/verify/integrations/aspnet-core-v6/?verify_domain=super.criipto.id&verify_client_id=urn:grn:my:application:90000#configure-openid-connect-middleware
Against https://deploy-preview-33--criipto-docs.netlify.app/verify/integrations/aspnet-core-v6/#configure-openid-connect-middleware
Please rebase when merging to cleanup test commits.
=> Embeddable URL params for easier guides

graphql-signatures-types.ts, src/components/Navigation.tsx, src/pages/verify/e-ids/belgian-eid.mdx, src/pages/verify/e-ids/danish-mitid.mdx, src/pages/verify/e-ids/danish-nemid.mdx, src/pages/verify/e-ids/finnish-trust-network.mdx, src/pages/verify/e-ids/index.mdx, src/pages/verify/e-ids/itsme.mdx, src/pages/verify/e-ids/norwegian-bankid.mdx, src/pages/verify/e-ids/norwegian-vipps.mdx, src/pages/verify/e-ids/sofort.mdx, src/pages/verify/e-ids/swedish-bankid.mdx, src/pages/verify/integrations/javascript.mdx, src/pages/verify/integrations/react.mdx, src/snippets/login-methods-and-path-encoded.mdx, src/snippets/login-methods.mdx, src/utils/auth-methods.ts
Part two: change category 
(+ couple a e-IDs from part one)
=> change category to eIDs

src/pages/verify/e-ids/danish-mitid.mdx
@sgryt Perhaps you can supplement with some more formal differences?
=> add explainer for MitID low vs substantial

src/pages/verify/e-ids/danish-mitid.mdx
recommendation about full-viewport for mobile
=> Update danish-mitid.mdx with min size reqs and a

src/pages/verify/e-ids/danish-mitid.mdx
and added a link to the guide for appswitching.
=> Correcting a few ambiguous usages of 'web view'

src/pages/verify/getting-started/oidc-intro.mdx
Some suggestions for changes to the "Using OpenID Connect" section: add a brief description of supported OIDC flows.
=> OIDC flows: add intro

src/pages/verify/e-ids/danish-mitid-erhverv.mdx
Merge when https://github.com/GreanTech/identityprovider/pull/679 has been QA'ed and released.
=> Added doc for the new 'employee' claim for MitID Erhverv

src/pages/verify/guides/custom-styling.mdx
Do not merge until feature is live.
=> custom-ui: document i18n tag

src/pages/verify/e-ids/danish-mitid.mdx
This is only for outbound flows for now, since we do not yet support inbound flows.
=> Add docs on MitID Controlled Transfer.

src/pages/verify/e-ids/danish-mitid-erhverv.mdx
- Activation emails are still expected to arrive (but seem unreliable);
- It's possible to activate a user by logging in to EIA even without an activation email: I added a note about it. 
Last Friday, I was getting errors trying to log in as an employee as described, but it works today.
=> MitID Erhverv test user creation guide update

src/components/AuthorizeURLBuilder.tsx
=> Added nonVisibleData to skip-list in the authorize request URL link

src/pages/verify/e-ids/dutch-idin.mdx, src/utils/auth-methods.ts
Authorize URL builder accordingly.
=> Added example of the acr_values for iDIN, and extended the

src/pages/verify/e-ids/danish-mitid.mdx
=> MitID test app: add a note about test and production versions

src/examples/addSignatory/overrideEvidenceProviderSettings.cs, src/examples/addSignatory/overrideEvidenceProviderSettings.graphql.ts, src/examples/addSignatory/overrideEvidenceProviderSettings.node.ts, src/examples/addSignatory/overrideEvidenceProviderSettings.ts, src/pages/signatures/graphql/examples.mdx
Create section for overriding evidence provider settings per signatory and add examples.
=> Add docs for overriding signatory EP settings

src/pages/verify/e-ids/german-personalausweis.mdx
Adds information on:
- Configuring a static scope in the Dashboard
- Manually overriding flow selection
=> Add more information to Personalausweis.

src/components/AuthorizeURLBuilder.tsx, src/pages/changelog/2025-04-25.mdx, src/pages/verify/e-ids/frejaid.mdx, src/pages/verify/guides/choose-language.mdx, src/snippets/jwt-payloads/swedish-frejaid.mdx, src/utils/auth-methods.ts
Details about how to configure the app for testing and how to create test users with specific levels
of access.
=> Add Freja docs.

src/pages/verify/guides/custom-styling.mdx
=> Added (brief) description about Content-Security-Policy considerations

src/pages/verify/e-ids/finnish-trust-network.mdx
This is the first draft of the FTN Requirements section. 
I'll add links to explanatory blog posts once we publish them. Links to the technical guides also pending.
=> Add FTN requirements

src/pages/signatures/guides/custom-seals-page-template.mdx, src/pages/signatures/guides/eid-special-configuration.mdx, src/pages/signatures/guides/index.mdx
Also changed the order of the guides to place the Signatures API features before eID Special Configurations.
=> Update Guides index page to reference all guides.

src/pages/verify/e-ids/danish-mitid.mdx, src/pages/verify/e-ids/norwegian-bankid.mdx, src/pages/verify/e-ids/norwegian-vipps.mdx, src/pages/verify/e-ids/swedish-bankid.mdx
Updated email from support@criipto.com to new email orders@criipto.com where it's relevant
=> Update order email
