- src/pages/verify/guides/appswitch.mdx
Android, and also added samples for app-detection
Note: The link to the "Danish MitID" section under the "Web" section is broken, it points to the first heading with the same name under "Native".
Would be nice to avoid that without having to add artificial words to the headings.
> Added feedback from TransferGalaxy about the MitID switch-back on

- src/pages/verify/e-ids/danish-nemid.mdx
- src/pages/verify/e-ids/index.mdx
- src/pages/verify/e-ids/norwegian-bankid.mdx
- src/pages/verify/getting-started/basics.mdx
- src/pages/verify/getting-started/overview.mdx
- src/pages/verify/getting-started/token-contents.mdx
- src/pages/verify/guides/choose-language.mdx
- src/pages/verify/guides/prefilled-fields.mdx
- src/pages/verify/guides/production.mdx
- src/pages/verify/integrations/javascript.mdx
- src/pages/verify/integrations/react-native-expo.mdx
- src/pages/verify/integrations/react.mdx
- src/pages/verify/integrations/vuejs.mdx
NemID page is not shown in the navigation (changed category to `eIDs(legacy)`).
Changed NemID to MitID where applicable. 
**Todo:**
- Update URL Builder
- Remove NemID page
- Update token-contents page (remove NemID, use JWTViewer)
- Remove NemID from login-methods
> Removing NemID content: hide from nav

- src/pages/verify/e-ids/norwegian-bankid.mdx
The Biometrics app doesn't have support for synthetic SSNs. 
So when generating a test user, the "Synthetic" box should be unchecked.
> BankID NO: add a note about synthetic SSNs

- src/pages/verify/integrations/react.mdx
Porting over the same fixes from the readme of https://github.com/criipto/criipto-verify-react/pull/32 to the docs website
> Fix react integration documentation for criipto verify: Add missing return statements and remove surpurflous else/else-if statements

- src/pages/verify/e-ids/swedish-bankid.mdx
- src/pages/verify/getting-started/basics.mdx
- src/pages/verify/getting-started/best-security-practices.mdx
- src/pages/verify/getting-started/oidc-intro.mdx
- src/pages/verify/getting-started/rate-limiting.mdx
- src/pages/verify/getting-started/token-contents.mdx
- src/pages/verify/integrations/javascript.mdx
- src/pages/verify/integrations/vuejs.mdx
1. Added OIDC best security practices guide.
2. Updated the **Using OpenID Connect** section
- Moved flow types description to a separate section;
- Improved cross-referencing;
- Capitalized the names of the flows (_implicit flow_ => _Implicit Flow_) following OIDC specification;
- Change wording from Example _authentication_ URL to Example _authorization_ URL, and updated linking;
3. Updated links to reflect the changes. 
4. Some minor typos are fixed.
UPD: included a note about using PKCE and `nonce` alongside one another (and not as an alternative) based on [PKCE vs. Nonce: Equivalent or Not?](https://danielfett.de/2020/05/16/pkce-vs-nonce-equivalent-or-not/)
> Add OIDC best security practices guide

- src/pages/verify/e-ids/danish-mitid.mdx
Describes the content of the `mitid:ct:sid:exp` claim and adds a suggestion for how to handle expiration of Controlled Transfer session tokens.
> Add documentation for mitid:ct:sid:exp

- src/components/AuthorizeURLBuilder.tsx
- src/pages/verify/e-ids/swedish-bankid.mdx
login_hint values for SE BankID.
For the authorize URL builder changes, I used the current docs for the `message` parameter as inspiration, but may have missed something.
> Attempt to document the coming nonVisibleData parameter in

- src/pages/verify/e-ids/danish-mitid.mdx
- src/pages/verify/e-ids/norwegian-bankid.mdx
- src/snippets/login-methods-and-path-encoded.mdx
- src/snippets/login-methods.mdx
Markdown tables were broken by a recent dependency upgrade. This fixes them by converting them to HTML tables.
> Fix table layouts.

- src/pages/verify/guides/test-users.mdx
While working on the new Dashboard homepage design and content, we realized we're missing a dedicated page for creating test users. Currently, we have to link to the [eIDs page](https://docs.criipto.com/verify/e-ids/) and ask users to find their way from there, which isn't ideal. 
I'm adding a page with direct links to the testing instructions.
> Add test users page

- src/components/Header.tsx
- src/components/Navigation.tsx
1. Currently, when a navigation link is clicked on mobile, side navigation remains open. I added `onLinkClick` callback and used it in `MobileNavigation` so that navigating to a page closes side navigation.
2. On mobile, long titles in the top nav are breaking the layout. Updated styles fix this (see screenshots).
3. Fixed Verify/Signatures dropdown to close when a product is selected
> Close sidenav on navigation link click (on mobile) + fix layout for long titles in the top nav on mobile

- src/pages/verify/integrations/index.mdx
Solved by adding `contentFilePath` to `pageQuery`
> Fix Integrations page displaying index.mdx in a list of integrations

- src/utils/auth-methods.ts
> Fix scope values in Authorize URL builder for Personalausweis.

- src/components/MdxProvider.tsx
We noticed that SVG icons in `Highlight` initially loaded at incorrect size: a huge icon appearing for the first second before resizing correctly can be spotted at [German Personalausweis](https://docs.criipto.com/verify/e-ids/german-personalausweis/) and [Norwegian BankID](https://docs.criipto.com/verify/e-ids/norwegian-bankid/)) pages. 
Fixed by adding inline `height` to the icon.
_Strangely, I couldn't reproduce the bug on localhost — only in production and deploy previews._
> Fix svg styles (currently loading wrong icon size)

- src/pages/verify/e-ids/danish-mitid-erhverv.mdx
The previous documentation was not clear about the differences between CPR number usage and data sources for the employee and company signatory roles.
This adds some explanation of the roles and the differences in usage of CPR numbers.
> Clarify MitID Business roles.

- gatsby-browser.tsx
- gatsby-ssr.tsx
- src/components/GraphQLExplorer.tsx
- src/components/Navigation.tsx
- src/layouts/fullscreen.tsx
- src/pages/signatures/graphql/endpoints.mdx
- src/pages/signatures/graphql/explorer.mdx
Rather than connecting to the GraphQL Explorer at signatures-api, we can just connect directly using the same capabilities that are used for examples.
This simplifies and centralizes how one interacts with the GraphQL interface.
> Inline Signatures GraphQL Explorer as part of docs

- src/components/GraphQLSchema.css
- src/components/GraphQLSchema.tsx
- src/pages/signatures/graphql/schema.mdx
- tsconfig.json
so that users may explore the schema types without having to submit credentials to the explorer
> add graphql schema page

- src/components/InteractiveTour.tsx
- src/examples/createBatchSignatory/BatchSignatoryInteractiveTour.tsx
- src/pages/index.mdx
- src/pages/signatures/getting-started/document-lifecycle.mdx
- src/pages/signatures/getting-started/graphql-primer.mdx
- src/pages/signatures/getting-started/interactive-tour.mdx
- src/pages/signatures/getting-started/register-application.mdx
- src/pages/signatures/getting-started/ui-customization.mdx
- src/pages/signatures/graphql/examples.mdx
- src/pages/signatures/guides/PdfFormFillingTour.tsx
- src/pages/signatures/index.mdx
Noticed some typos in the docs while writing sales material for Criipto Signatures.
> Fix typos and slightly update phrasing in Signatures

- src/pages/signatures/guides/eid-special-configuration.mdx
In some cases, eID requires some additional configuration to provide information such as names for the signature seals. The page describes some additional configuration required for German Personalausweis, Dutch iDIN and FrejaID.
> Add page on eID caveats for Signatures

- src/components/Header.tsx
This PR adds cmd+k (mac) / ctrl+k (non-mac) as a shortcut to open the header search box, and adds a small badge to the search input showing this shortcut
Someone with access to a windows computer (@mickhansen) please try triggering the search with ctrl+k to verify that it works
Note: I changed the event from keyup to keydown to make it work (which is also better practice to use nevertheless)
> Open search with cmd/ctrl+k

- src/examples/addSignatory/documents.graphql.ts
We're using the signature order with 2 documents to demonstrate that one can add a subset of documents to a signatory. However, it breaks the mutations where a signature order is created with a single document. This PR fixes that.
> Fix document index

- src/pages/signatures/guides/eid-special-configuration.mdx
Due to change in regulations, JWTs are now signed and encrypted for FTN, thus, consumers will need to get the claims from the new `claims` field instead of parsing the `jwt` themselves.
> Add section on handling JWT claims for FTN eID

- src/pages/verify/e-ids/frejaid.mdx
This is not documented in Freja's documentation, but we must request this to be enabled in production for our customers before it will work.
> Add document photo to Freja restricted attrs.

- src/pages/verify/guides/appswitch.mdx
- src/pages/verify/integrations/react-native-expo.mdx
- src/pages/verify/integrations/react.mdx
* App switching for SE BankID relies in a browser-less flow. This has very nice UX, but it is insecure, because a malicious app could initiate and complete the flow. So let's remove the docs.
* Removing docs on app detection, since they are no longer relevant
* Cleaning up the app switch docs
* Mention that there are two distinct flows
* Remove the mention of `SFAuthenticationSession` (which is deprecated). MitID [requires iOS 15](https://www.mitid.dk/hjaelp/hjaelpeunivers/tekniske-krav/), so `ASWebAuthenticationSession` is always available.
I'm wondering if it even makes sense to mention custom tabs / `ASWebAuthenticationSession` here? 🤔 They are not specifically required for app switching to work, but more of a general implementation detail when working with OIDC in native apps. …
> Update app switching docs

- src/pages/verify/e-ids/finnish-trust-network.mdx
the requirements are now enforced, so clients
no longer need explicit flags to test enforcement.
wording changed to be past-tense
> update FTN requirements to be past tense

- src/pages/verify/e-ids/norwegian-bankid.mdx
create a production domain in Criipto Verify before ordering credentials, in contrast to having a production domain ready in their own service/website/platform/...
The current wording is not abundantly clear here, and one must read the linked-to document to figure it out. 
Inspired by a question from Settla (via Håkon).
> Attempt to be more specific about the fact that customers must
